import { Geist } from "next/font/google";
import { Toaster } from "~/components/ui/sonner";
import { TRPCReactProvider } from "~/trpc/react";

import "~/styles/globals.css";

const geist = Geist({
	subsets: ["latin"],
});

export const metadata = {
	title: "Next.js",
	description: "Generated by Next.js",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<head>
				<title>Dashed</title>
				<meta name="description" content="Dashed" />
			</head>
			<body className={geist.className}>
				<TRPCReactProvider>
					<main className="flex min-h-screen flex-col items-center p-2 pb-16">
						{children}
					</main>
				</TRPCReactProvider>
				<Toaster
					toastOptions={{
						className:
							"bg-background/80 backdrop-blur-sm border-border text-foreground",
					}}
				/>
			</body>
		</html>
	);
}
